version: "3.9"
services:
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - php
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html

  php:
    build: ./docker/php
    expose:
      - 9000
    volumes:
      - ./src:/var/www/html
